Categories:
  - Sports & Health
License: GPL-3.0-only
AuthorName: Zoff
SourceCode: https://github.com/zoff99/UnderEat
IssueTracker: https://github.com/zoff99/UnderEat/issues
Changelog: https://github.com/zoff99/UnderEat/commits/master/

AutoName: Under Eat

RepoType: git
Repo: https://github.com/zoff99/UnderEat

Builds:
  - versionName: 1.0.4
    versionCode: 10004
    commit: b1ae99a2e948157b6f028c62804a64e67afbaaa1
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.5
    versionCode: 10005
    commit: 4403a4281fa5922eb032451dff468b37db7373e0
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.7
    versionCode: 10007
    commit: a0772206c5c97bd888bb4b21dae4d2f558780baa
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.8
    versionCode: 10008
    commit: cc10d83da2cfe40223f3900042e5daae90cd063c
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.11
    versionCode: 10011
    commit: edc8a4537297fa49ede1f839ec74288c9e468688
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.12
    versionCode: 10012
    commit: 1eabbe9f6673528973cb623903b48c24810aafec
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.13
    versionCode: 10013
    commit: c7aa9a1b1fc95ca96f8c0dd4471fb15893047e54
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.14
    versionCode: 10014
    commit: 26cafa12c0a71dd0b7f8b1e2fbbc05095e0ac7a1
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.15
    versionCode: 10015
    commit: be60fecdd9d236a0cf9efbb67e5dc3e101d42d23
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags ^[0-9].*
CurrentVersion: 1.0.15
CurrentVersionCode: 10015
