Categories:
  - File Transfer
  - Internet
License: GPL-3.0-only
AuthorName: Zoff
SourceCode: https://github.com/zoff99/ToFShare
IssueTracker: https://github.com/zoff99/ToFShare/issues
Changelog: https://github.com/zoff99/ToFShare/commits/master/

AutoName: ToFShare

RepoType: git
Repo: https://github.com/zoff99/ToFShare.git

Builds:
  - versionName: 1.0.3
    versionCode: 10003
    commit: 2a06497059991c174aefdc58ab9c1a356161c76d
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.4
    versionCode: 10004
    commit: c511c657d61a46b476d8404200a941c2130ea941
    subdir: android-refimpl-app/app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags ^[0-9].*
CurrentVersion: 1.0.4
CurrentVersionCode: 10004
