Connectivity:
  name: Tengingar
Development:
  name: Þróun
Games:
  name: Leikir
Graphics:
  name: Myndefni
Internet:
  name: Internetið
Money:
  name: Fjármál
Multimedia:
  name: Margmiðlun
Navigation:
  name: Yfirsýn
Phone & SMS:
  name: Símar og SMS
Reading:
  name: Lestur
Science & Education:
  name: Menntun og vísindi
Security:
  name: Öryggi
Sports & Health:
  name: Íþróttir og heilsa
System:
  name: Kerfið
Theming:
  name: Þemu
Time:
  name: Tími
Writing:
  name: Skrifa
App Store & Updater:
  name: Forritasafn og uppfærslur
Bookmark:
  name: Bókamerki
Browser:
  name: Vafri
Calculator:
  name: Reiknivél
Calendar & Agenda:
  name: Dagatal og dagskrá
Cloud Storage & File Sync:
  name: Geymsla á tölvuskýi og samstilling skráa
DNS & Hosts:
  name: DNS & Hýsingar
Draw:
  name: Teikna
Ebook Reader:
  name: Rafbókalesari
Email:
  name: Tölvupóstur
File Encryption & Vault:
  name: Dulritun skráa og lykilorðageymsla
File Transfer:
  name: Skráaflutningur
Finance Manager:
  name: Fjármálaumsýsla
Forum:
  name: Spjallsvæði
Gallery:
  name: Myndasafn
Habit Tracker:
  name: Venjuskráning
Icon Pack:
  name: Táknmyndapakki
Keyboard & IME:
  name: Lyklaborð og innsláttur
Launcher:
  name: Ræsir
Local Media Player:
  name: Margmiðlunarspilari á tæki
Location Tracker & Sharer:
  name: Staðsetningarrakning og deiling
Messaging:
  name: Skilaboð
Music Practice Tool:
  name: Tónlistaræfingatól
News:
  name: Fréttir
Note:
  name: Minnispunktur
Online Media Player:
  name: Margmiðlunarspilari á neti
Pass Wallet:
  name: Lykilorðaveski
Password & 2FA:
  name: Lykilorð og 2FA
Podcast:
  name: Hlaðvarp
Public Transport:
  name: Almenningssamgöngur
Recipe Manager:
  name: Uppskriftasafn
Shopping List:
  name: Innkaupalisti
Social Network:
  name: Samfélagsnet
Task:
  name: Verkefni
Text Editor:
  name: Textaritill
Translation & Dictionary:
  name: Þýðingar og orðasafn
Unit Convertor:
  name: Einingaumbreytir
Voice & Video Chat:
  name: Tal- og myndspjall
VPN & Proxy:
  name: VPN og milliþjónn
Wallet:
  name: Veski
Wallpaper:
  name: Bakgrunnsmynd
Weather:
  name: Veður
Workout:
  name: Líkamsrækt
