Ads:
  description: Cette application comporte des publicités
  name: Publicités
DisabledAlgorithm:
  description: La signature de sécurité de cette application est faible
  name: Signé par un algorithme NON sécurisé
KnownVuln:
  description: Cette application présente une faille de sécurité connue
  name: Vulnérabilité connue
NSFW:
  description: Cette application utilise des contenus qui ne devraient pas être rendus publics ni être visibles n’importe où
  name: NSFW (non sûr pour le travail)
NoSourceSince:
  name: Aucune source depuis
  description: Le code source n'est plus disponible, aucune mise à jour possible
NonFreeAdd:
  description: Cette application promeut des extensions propriétaires
  name: Extensions non libres
NonFreeAssets:
  description: Cette application comprend des éléments propriétaires
  name: Composants propriétaires
NonFreeDep:
  description: Cette application s'appuie d'autres applications propriétaires
  name: Dépendances propriétaires
NonFreeNet:
  description: Cette application dépend entièrement ou promeut l'utilisation de services en réseau propriétaires
  name: Services en réseau propriétaires
Tracking:
  description: Cette application suit et transmet votre activité
  name: Traçage
TetheredNet:
  description: Cette application dépend entièrement d'un service en réseau spécifique
  name: Services en réseau inféodés
