Connectivity:
  name: Connettività
Development:
  name: Sviluppo
Games:
  name: Giochi
Graphics:
  name: Grafica
Internet:
  name: Internet
Money:
  name: Finanze
Multimedia:
  name: Multimedia
Navigation:
  name: Navigazione
Phone & SMS:
  name: Telefono e SMS
Reading:
  name: Lettura
Science & Education:
  name: Scienza ed educazione
Security:
  name: Sicurezza
Sports & Health:
  name: Sport e salute
System:
  name: Sistema
Theming:
  name: Personalizzazione
Time:
  name: Tempo
Writing:
  name: Scrittura
Bookmark:
  name: Segnalibri
Calculator:
  name: Calcolatrice
Ebook Reader:
  name: Lettore di Ebook
Email:
  name: Email
Gallery:
  name: Galleria
Icon Pack:
  name: Pacchetto di icone
Messaging:
  name: Messaggi
News:
  name: Notizie
Note:
  name: Appunti
Podcast:
  name: Podcast
Shopping List:
  name: Lista della spesa
Social Network:
  name: Social Network
Unit Convertor:
  name: Convertitore di unità
Weather:
  name: Meteo
App Store & Updater:
  name: App Store & Aggiornamenti
Browser:
  name: Browser
Calendar & Agenda:
  name: Calendario & Agenda
Cloud Storage & File Sync:
  name: Archiviazione Cloud & Sincornizzazione dei File
DNS & Hosts:
  name: DNS & Hosts
Draw:
  name: Disegna
File Transfer:
  name: File Transfer
Finance Manager:
  name: Finanza
Forum:
  name: Forum
Keyboard & IME:
  name: Tastiera e Metodi di Inserimento
Launcher:
  name: Launcher
Local Media Player:
  name: Lettore Media Locali
Music Practice Tool:
  name: Strumento per la Pratica Musicale
Online Media Player:
  name: Lettore Media Online
Pass Wallet:
  name: Portafogli Pass
Password & 2FA:
  name: Password & Autenticazione a 2 Fattori
Public Transport:
  name: Trasporti Pubblici
Recipe Manager:
  name: Gestore Ricette
Task:
  name: Task
Text Editor:
  name: Editor di Testo
Translation & Dictionary:
  name: Traduzione & Dizionario
Voice & Video Chat:
  name: Chat Vocale & Video
VPN & Proxy:
  name: VPN & Proxy
Wallet:
  name: Portafoglio
Wallpaper:
  name: Sfondo
Workout:
  name: Allenamento
File Encryption & Vault:
  name: Criptatore di File & Archivio Nascosto
Habit Tracker:
  name: Monitor Abitudini
Location Tracker & Sharer:
  name: Localizzatore & Condivisione
